sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dantedxwolf -f Dockerfile.dev .

script:
  - docker run -e CI=true dantedxwolf npm run test
deploy:
  provider: heroku
  api_key: "49f867e6-ec44-4eea-a3b9-34ca1ef382ee"