sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dantedxwolf -f Dockerfile.dev .

script:
  - docker run -e CI=true dantedxwolf npm run test
deploy:
  provider: heroku
  api_key: "$herokuAPI"
  app: "dry-basin-93823"